### ISSUE TITLE
acceleration pipe & colored pipe crashing game

### ISSUE THREAD

**Issue by beyondthewall** [TeamBR-Modding/NeoTech#33] opened 2015-09-10 05:57 UTC
as soon as i connect an acceleration pipe with any colored pipe the game crashes. with white pipes or only acceleration pipes and extraction and insertation pipes it works as expected. (this happens in singleplayer, i didnt try this in multiplayer)

**Comment by Dyonovan** [comment] 2015-09-10 13:39
Need a copy of the crash log. Please use pastebin

**Comment by beyondthewall** [comment] 2015-09-10 15:31
same here. :)
client log: http://pastebin.com/raw.php?i=PYxvtSL4

**Comment by Dyonovan** [comment] 2015-11-28 18:31
Dupe of #32. Working on fixing it now

**Closed as completed by Dyonovan** 2015-11-28 18:31 UTC
