### ISSUE TITLE
Items spewing everywhere

### ISSUE THREAD

**Issue by Berserker66** [TeamBR-Modding/NeoTech#117] opened 2016-02-16 01:29 UTC
Example: inventory which provides coal. A length of pipe to a furnace input.

Coal will go into the furnace. Once it's full, all in transit coal will just spew into the world upon arriving.

**Comment by pauljoda** [comment] 2016-02-16 02:45
Again, this issue is fixed from what I can tell. Please provide a version number

**Comment by Berserker66** [comment] 2016-02-16 03:18
Whatever your latest version is on curse.

**Comment by Darktotaled** [comment] 2016-02-16 03:20
i was having this problem in 2.3.5 with item pipe and hopper. I had a crusher>pipe>furnace>dimensional crates setting and on top of the furnace and crusher i had hoppers. When the content of the furnace goes out and it's empty the hopper puts an item in the furnace and the pipe throw a item too. the item that comes from the pipe has nowhere to go so it flies away like a butterfly :D Seems pretty right?

**Comment by pauljoda** [comment] 2016-02-16 03:24
The issue you are having @Darktotaled is related to the two trying to send stuff at the same time. When my pipe decides to send, it has to take a snapshot of the tile entity and see if it can accept what the extraction is sending. This also handles simulating all things coming its way. However, if you change the tile while this is happening it will simulate a success that will be invalidated by the time it gets there. There is no way for me to prevent this from happening. I can't just have the resource decide to turn around and go home. I have done all I can, it is now up to the user to set up an efficient system. There is only so much I can do from the code side of things

**Comment by pauljoda** [comment] 2016-02-16 03:26
This was fixed in 2.3.6

**Closed as completed by pauljoda** 2016-02-16 03:26 UTC

**Comment by Darktotaled** [comment] 2016-02-16 03:29
Was thinking about the item keep going back and forth inside the pipe till it gets clear to go but i'll stick with you and it will be better if people thing about the design instead of just throwing machine over machine. Thanks @pauljoda amazing as always

**Comment by Berserker66** [comment] 2016-02-16 08:49
Manually updated to 2.3.6. While some issues are fixed, items are still spewing forth the piping.

**Comment by pauljoda** [comment] 2016-02-16 17:11
Can you provide a screen shot of your setup

**Comment by Berserker66** [comment] 2016-02-16 17:33
The item pipe on the coal drawer is both input and output
![2016-02-16_18 28 54](https://cloud.githubusercontent.com/assets/3189725/13084805/65f91daa-d4db-11e5-879e-bbb6857eba25.png)
![2016-02-16_18 29 25](https://cloud.githubusercontent.com/assets/3189725/13084804/65f7984a-d4db-11e5-9872-ecab12610cca.png)

Basically the coal on the essentia smeltery will not stop in time, the flow is stopped once the smelter has a full stack of coal, but anything else will just spew out.

It was much worse when I had pipes mixed with thaumcraft golems, but I removed those.

**Comment by Darktotaled** [comment] 2016-02-16 17:37
you use interface pipes all the way to the essentia smeltery? It's strange, mine is working normally.

**Comment by Darktotaled** [comment] 2016-02-16 17:38
I'll try to reproduce it here

**Comment by Berserker66** [comment] 2016-02-16 17:43
There's a hungry chest as input in the network, where anything an arcane bore mines comes in. From there things go into the electrical grinder and the storage drawers. The coal drawer is set as both input and output, to fuel the coal generator and essentia smelter as needed.

I didn't investigate it a lot, but I also had a case where the interface pipe linked to a thaumcraft item mirror and anything going into it was duped a few times. But that was before I updated, so it might be fixed now.

**Comment by Darktotaled** [comment] 2016-02-16 18:29
if the the coal is flying because of the smeltery it means that the interface pipe is trying to put coal in the upper slot and when something enter that slot with coal in the pipe it gets thrown away. You know coal can be smelted there for potentia and ignis. The interface pipes put items until there is no more valid slots for the item.

**Comment by Darktotaled** [comment] 2016-02-16 18:30
That's my conclusion with the little test i just made

**Comment by Berserker66** [comment] 2016-02-16 18:31
Fairly sure the bottom side of the smeltery is only supposed to accept fuel though.

**Comment by Darktotaled** [comment] 2016-02-16 18:35
Just tried that ^
and was able to reproduce your issue   http://prntscr.com/a43wvi
It seems the interface pipe is miscounting space in the inventory.
