### ISSUE TITLE
Either NeoTech 1.8-2.0.3 or BookshelfAPI 1.8-2.0.1 -- crashes client and server on startup

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#28] opened 2015-08-17 18:33 UTC
## SERVER

Issue: crash while starting dedicated server looking for missing classes

crash report:
https://gist.github.com/e443b594cdad85871f75

fml server latest:
https://gist.github.com/cfded5622ab6a944b659
## CLIENT

Issue: crash while starting client looking for missing classes

crash report:
http://paste.ee/p/nrrcb

fml log: 
http://paste.ee/p/qfAWa

**Comment by Dyonovan** [comment] 2015-08-17 18:49
Where are you getting BookShelf from? The file that we distribute through curse is Bookshelf-1.8-2.0.1.jar. http://minecraft.curseforge.com/mc-mods/232784-bookshelf-api-library/files/2252669

The one in your crash log is bookshelf-api-1.8-2.0.1.jar

Are you renaming it or are you using the wrong one? If that is the case, I might need to change the mod-id to make it unique

**Comment by Dyonovan** [comment] 2015-08-17 19:40
Ok tracked it down:

Caused by: java.lang.NoClassDefFoundError: com/dyonovan/neotech/handlers/ItemHandler
    at the_fireplace.unlogicii.recipes.NeoTechRecipes.<init>(NeoTechRecipes.java:8)

You have a mod thats trying to use the OLD version of neotech. They are going to have to update

**Comment by kreezxil** [comment] 2015-08-17 19:47
I'm renaming it. I'm getting it from curseforge.

**Comment by Dyonovan** [comment] 2015-08-17 19:59
How about the other mod? Does removing it fix the issue with NeoTech?

**Comment by kreezxil** [comment] 2015-08-17 20:10
Issue: removed unlogic II and while the client doesn't crash now, the server is still crashing on startup

crash report:
https://gist.github.com/45866fdd690c9daedeb7

fml server latest:
https://gist.github.com/ada1a0308df40126d4ca

**Comment by Dyonovan** [comment] 2015-08-17 21:40
Ok. I think I fixed it. At least it isnt crashing for me anymore.

Try this and let me know http://www.beyondrealitypack.com:8080/job/NeoTech/160/

I am also sitting in your TeamSpeak :P

**Comment by kreezxil** [comment] 2015-08-18 01:44
Using that version I get fatally missing blocks when trying to connect to the server

```
[20:41:01] [Netty Client IO #1/DEBUG] [FML/]: Missing list: [neotech:pipeFluidBasicSink, neotech:pipeFluidBasicSource, neotech:pipeFluidBasicSource, neotech:pipeFluidBasicSink]
[20:41:01] [Netty Client IO #1/DEBUG] [FML/]:   Next: ERROR
[20:41:01] [Netty Client IO #1/DEBUG] [FML/]: FMLHandshakeClientState: $HandshakeAck:{2}->FMLHandshakeClientState$8:ERROR
[20:41:01] [Netty Client IO #1/DEBUG] [FML/]:   Next: ERROR
[20:41:04] [Client thread/INFO] [Schematica/]: Client settings have been reset.
[20:41:29] [Client thread/INFO] [LiteLoader/]: LiteLoader is shutting down, shutting down core providers and syncing configuration
[20:41:29] [Client thread/INFO] [LiteLoader/]: Baking listener list for ShutdownObserver with 3 listeners
```

**Comment by Dyonovan** [comment] 2015-08-18 02:31
ok. I am pretty sure its fixed. That error is due to the fact we are in the middle of implementing pipes. Shouldnt be to long till we have a release. Keep you eye on that jenkins tho

**Comment by Dyonovan** [comment] 2015-08-18 14:11
Should be fixed in the new versions of Neotech and Bookshelf I just published. Let me know

**Closed as completed by Dyonovan** 2015-08-18 14:11 UTC
Labels: bug

**Comment by kreezxil** [comment] 2015-08-19 00:54
It's looking good now. Thanks.

**Comment by Dyonovan** [comment] 2015-08-19 00:55
Ok good. Let me know if any other issues happen

**Comment by kreezxil** [comment] 2015-08-21 18:10
will do
