### ISSUE TITLE
Item Interface Pipe won't connect to most modded inventories

### ISSUE THREAD

**Issue by Amperthorpe** [TeamBR-Modding/NeoTech#223] opened 2016-03-13 19:23 UTC
What Version of NeoTech are you using: 2.4.1

If possible, did you break and replace the block: Yes.

No crash.

http://i.imgur.com/VaQzyOY.png

**Comment by pauljoda** [comment] 2016-03-13 19:31
None are using IItemHandlers I assume. We only work with the new forge standard. You'll have to wait for those to update

**Comment by dannydjdk** [comment] 2016-03-13 22:00
This may only be visual. While I'm experiencing the same visual effect in NeoTech 2.4.1 with EZ Storage 1.2.6, items are still routing correctly.

**Comment by pauljoda** [comment] 2016-03-15 20:02
Closing this as not an issue, the issue is other mods are not implementing the new system correctly. Give them time and they will update I'm sure

**Closed as completed by pauljoda** 2016-03-15 20:02 UTC

**Comment by raoulvdberge** [comment] 2016-05-22 02:56
Can't you use InvWrapper / SidedInvWrapper for this? You'll still use an IItemHandler _and_ have compatibility with mods that still use IInventory / ISidedInventory.

This is a little snippet I use:

``` java
    public static IItemHandler getItemHandler(TileEntity tile, EnumFacing side) {
        if (tile == null) {
            return null;
        }

        IItemHandler handler = tile.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, side);

        if (handler == null) {
            if (side != null && tile instanceof ISidedInventory) {
                handler = new SidedInvWrapper((ISidedInventory) tile, side);
            } else if (tile instanceof IInventory) {
                handler = new InvWrapper((IInventory) tile);
            }
        }

        return handler;
    }
```

**Comment by pauljoda** [comment] 2016-05-22 03:08
Yes I could that is not the issue. Forge has stated to stop supporting those methods. While it may add compatibility with other mods, it also encourages those mods not to update. We will do things the way forge intends and other mods will have to do the same. There is no point in supported depreciated classes

**Comment by raoulvdberge** [comment] 2016-05-22 20:12
Alright, I understand that. I have a small question about the interface pipes.

[Why do you expect a destination tile to implement IItemHandler?](https://github.com/TeamBR-Modding/NeoTech/blob/1.9/src/main/scala/com/dyonovan/neotech/pipes/tiles/item/ItemInterfacePipe.scala#L56). Why aren't you using `getCapability` there? Thanks.
