### ISSUE TITLE
Sugestions so far

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#129] opened 2016-02-17 18:06 UTC
Items:
- ~~Gravity Manipulator(for flying)~~ 
- ~~NeoTechSuit and it's Upgrades~~ These two are in one, electric armor implemented. Jetpack and gliding abilities working
- Instructions Book
- Metal Boat for romantic lava rides in the nether
- Energy Gun

Blocks:
- Elevators
- Tidal/Hydro Generators
- Windmills
- Sun-Powered Machines
- Multiblock Greenhouse
- Harvester Machine
- Cobblestone and other types of rock Generator Machine
- Dimensional Crates upgrades
- Dyable Cement blocks for decoration and ~~cover System~~ Multipart integration, this is the cover system (use chisel and bits)
- Time-Space Manipulator and markers( for moving entire constructions)
- Teleportation Chamber
- Transmitter Device

Fuel:
- Ethanol
- Biomass
- Composite Explosive Fuel
- Heat
- Steam
- Mob Drops
- Coal+Water Mix

Metals and Alloys:
- Titanium
- Aluminum
- Nickel
- Zinc
- Invar
- Brass
- ~~Steel~~ Done
- Conductant Ingot

Updates:
- ~~New Energy Bar http://prntscr.com/a4j0x6~~ Done
- ~~Tiered Machines~~ 
- Processing Dyes in the Crusher
- Have an option on the Mob Stand for a continual rotation/spinning of the model.

I guess this is it @Dyonovan  and @pauljoda

**Comment by Berserker66** [comment] 2016-02-17 20:06
Personally not a fan of tiered machines. I like upgrades, like how ender io or mekanism do it.

**Comment by Darktotaled** [comment] 2016-02-17 20:51
I'd love both together. So i could take it to the extreme levels of performance.

**Comment by Darktotaled** [comment] 2016-02-17 21:00
Tiered machines as I mentioned would be an upgraded version of the machine. For example, an advanced electric Furnace would smelt 2 items at a time, all upgrades would be normal and Expansion upgrade would give the ability of 5% for extra item for every process. The machine would have different base stats like internal energy buffer higher, energy consumption higher and the list goes on.

**Comment by Berserker66** [comment] 2016-02-17 21:06
So, Mekanism.

**Comment by Darktotaled** [comment] 2016-02-17 21:09
Sort of, @Berserker66 . When they add a mining machine we will need a lot of processing power. I like how the upgrades work now and i dont want to mess with them, so i wanted a better platform for them. It's a good way to use them

**Comment by pauljoda** [comment] 2016-02-18 05:24
Right now I'm working on an electric crucible that will allow you to melt down metals. If you interested in the metals we have, check the lastest build on jenkins. We have: copper, tin, lead, silver (those ore gen) bronze, gold, iron, (gold and iron just add what is missing from vanilla), and steel. I think thats it. @Dyonovan made me stop adding fluids because I made a fun new tool that makes it easy and got carried away. Let us know where we should go with those metals as base

**Comment by Berserker66** [comment] 2016-02-18 09:45
You have both gold and silver, which makes electrum and is used in many mods, so I'd recommend adding that to the list.

**Comment by Darktotaled** [comment] 2016-02-18 16:30
And lead is good to hold radiation that leads you to the Nuclear path

**Comment by winsrp** [comment] 2016-03-09 19:57
how about a block to charge RF stuff, like the battery and the mob catcher thing?

**Comment by pauljoda** [comment] 2016-03-09 20:26
That is the rf storage. It has charge slots

**Comment by winsrp** [comment] 2016-03-09 20:35
oh, that's what those holes are for... gotcha!

**Comment by winsrp** [comment] 2016-03-10 15:54
I have one, how about a priority order for power output, I see that machines closer to the power source have priority over machines far away, but most of the time things far away gather important resources for actual power generation. This could be part of the control module upgrades, just a number in the interface that allows you to set priority (yeah, not the same thing as channel), higher priority machines get power first and once they are depleted, move to the next lower number, where number 0 is the default and no priority... using the same current distribution format.

**Comment by winsrp** [comment] 2016-03-10 16:01
uhh another one... how about make the electric pump have an under level range too for lava, I think it does a 5x5 range, but only on the level where the pump pipe touches the lava, it could be nice if it started like 3 blocks below or something like that, and moves upwards. Playing in a hardcore server and having to pick everytime the pump finishes extracting lava is a pain in the ass.

Plan 2: How about adding upgrades to it, where you can specify if you want the block to be replaced with stone or not.. in case you select to not be replaced, it will just take that lava/water block out of the world, and once it finishes a level it will automatically move down since it will extend the pipe and naturally keep going.

Scrap this line, it is actually a bug. --------------------------------
Include in the upgrades plan making a longer pipe!!... just noticed it won't go down more than 2 blocks. 

Bug Details, how to reproduce -----------------
when you have a lava pool, 5x3x5 (x,y,z) , but the lower level is lava, the middle one glass, the upper one lava. Then you break the glass in the middle, so you have 5x5 lava, 5x5 air, 5x5 lava.

and the pump sucks the center block before finishing the upper level of the lava floor, (leaves one or more lava block without extracting), when you break the stone, the tube will just go down one block. instead of 2...

**Comment by DDzwiedziu** [comment] 2016-03-11 18:15
I propose that the binded motherboards could be upgraded further. I don't want to throw out 8 diamonds whenever I would need to add redstone control.

**Comment by pauljoda** [comment] 2016-03-11 18:16
You should be able to. Not sure if I messed up somewhere but that
functionality should he present

**Comment by DDzwiedziu** [comment] 2016-03-11 18:19
@pauljoda unfortunately no. A MB with 8 processors and I want to add 8 hard drives; there's no progress after clicking the start button and ticks don't go down (RF and tin present).
Latest FTB Unstable (2.4.1).
So, bug then?

**Comment by pauljoda** [comment] 2016-07-31 03:57
I'm closing this, but will still use for reference. Want to make way for new iteration suggestions

**Closed as completed by pauljoda** 2016-07-31 03:57 UTC
Labels: enhancement
