### ISSUE TITLE
Mod support for Mo' Shiz's Ores

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#15] opened 2015-07-04 00:44 UTC
There is a mod that I like using atm it is called Mo' Shiz mod and I was wondering if you would like to add in a way to get the crusher and the furnace to crush it up doubleing the copper and also a way to cook it up in that furnace. Right now that mod and this mod are incompatible seeing as the crusher won't crush Mo' Shiz's Ores and the Furnace won't smelt the crushed ores. Even though a regular furnace can.

**Comment by Dyonovan** [comment] 2015-07-04 02:31
Duplicate of #12

**Closed as completed by Dyonovan** 2015-07-04 02:31 UTC
